sudo: required
language: c

env:
  - CABALVER=1.22 GHCVER=7.10

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
  - cabal update
  - cabal configure
  - cabal install hspec

script:
  - cabal build
  # - runhaskell -isrc ./tests/ProductoTest.hs
  # - runhaskell -isrc ./tests/SumaTest.hs
