override SPHNX:=sphinx-build
override DOCSRC:=$(DOCS)/$(SRC)
override DOCBUILD:=$(DOCS)/$(BUILD)

.PHONY: docs html
html:
	$(SPHNX) -M $@ $(DOCSRC) $(DOCBUILD)
docs: html

.PHONY: test-docs
test-docs: html
	$(BROWSER) $(DOCBUILD)/$^/index.html
