version: 2
jobs:
  # Alexa Version - Unit Test
  # https://circleci.com/docs/2.0/language-javascript/
  unit_test:
    working_directory: ~/alexa/lambda/us-east-1_ask-custom-alexa-default
    docker:
      - image: circleci/node
    steps:
      # Clone the source code
      - checkout:
          path: ~/alexa
      # Update NPM to latest version
      - run:
          name: Update NPM
          command: sudo npm install --global npm@latest
      # Restore dependencies
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      # Upgrade/Install NPM modules
      - run:
          name: NPM Install
          command: npm install
      # Save updated dependencies
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: ./node_modules
      # Run the Unit Tests & Code Coverage
      - run:
          name: Unit Tests
          command: npm test
      # Run Coverage to Codecov.io
      - run:
          name: Code Coverage
          command: |
            npm install --global codecov
            npm run coverage
            codecov

# ====================================================================

workflows:
  version: 2
  builds:
    jobs:
      - unit_test:
          filters:
              branches:
                only: alexa
