version: 2
jobs:

  configure:
    docker:
      - image: fpco/stack-build
    steps:
      - run:
          name: Docker Container Downloader!
          command: echo "Hello World!"

  make_build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Check GHC
          command: ghc --version
      - run:
          name: Build Program
          command: make

  cabal_build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Check GHC and Cabal
          command: |
            ghc --version
            cabal --version
      - run:
          name: Configure Cabal
          command: |
            cabal update
            cabal configure --enable-tests
      - run:
          name: Build Program
          command: cabal build
      - run:
          name: Link the executable
          command: |
            sudo ln -s $PWD/dist/build/alfred/alfred /usr/bin/alfred
            alfred --version
      - save_cache:
          key: alfred-binary
          paths:
            - dist/build/alfred/alfred

  cabal_test:
    docker:
      - image: fpco/stack-build
    steps:
      - restore_cache:
          keys:
            - alfred-binary
      - run:
          name: Linking Alfred
          command: sudo ln -s $PWD/dist/build/alfred/alfred /usr/bin/alfred
      - run:
          name: Alfred Version
          command: |
            alfred -v
            alfred --version

workflows:
  version: 2
  builds:
    jobs:
      - configure:
          filters:
            branches:
              only: master
      - make_build:
          requires:
            - configure
      - cabal_build:
          requires:
            - configure
      - cabal_test:
          requires:
            - cabal_build
