version: 2
jobs:
  make_build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Check GHC
          command: ghc --version
      - run:
          name: Configure
          command: make configure
      - run:
          name: Build
          command: make build
      - run:
          name: Clean
          command: make clean
  cabal_build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Check GHC and Cabal
          command: |
            ghc --version
            cabal --version
      - run:
          name: Configure Cabal
          command: |
            cabal update
            cabal install hspec hspec-discover
      - run:
          name: Build Program
          command: cabal build
      - save_cache:
          key: alfred-binary-{{ checksum ".circleci/config.yml" }}-{{ checksum "src/core/Parser.hs" }}
          paths:
            - example
            - dist/build/alfred/alfred

  test_binary:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - restore_cache:
          keys:
            - alfred-binary-{{ checksum ".circleci/config.yml" }}-{{ checksum "src/core/Parser.hs" }}
      - run:
          name: Linking Alfred
          command: sudo ln -s $PWD/dist/build/alfred/alfred /usr/bin/alfred
      - run:
          name: Alfred Version
          command: |
            alfred -v
            alfred --version
      - run:
          name: Alfred Help
          command: |
            alfred -h
            alfred --help
      - run:
          name: Hello World
          command: alfred example/holamundo.alf
      - run:
          name: Variables
          command: alfred example/variables.alf
  test_code:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Cabal Dependencies
          command: |
          cabal update
          cabal install hspec hspec-discover
      - run:
          name: Alfred Cabal Tests
          command: cabal test
      - run:
          name: Alfred Binary Tests
          command: ./dist/build/alfred-test/alfred-test

workflows:
  version: 2
  builds:
    jobs:
      - make_build:
          filters:
            branches:
              only: master
      - cabal_build:
          filters:
            branches:
              only: master
      - test_binary:
          requires:
            - make_build
            - cabal_build
      - test_code:
          requires:
            - make_build
            - cabal_build
