version: 2.1
jobs:
  make_build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Check GHC
          command: ghc --version
      - run:
          name: Build Program
          command: make
  cabal_build:
    docker:
      - image: fpco/stack-build
    steps:
      - checkout
      - run:
          name: Check GHC and Cabal
          command: |
            ghc --version
            cabal --version
      - run:
          name: Configure Cabal
          command: |
            cabal update
            cabal configure --enable-tests
      - run:
          name: Build Program
          command: cabal build
  test:
    docker:
      - image: fpco/stack-build
    steps:
      # Check the Github files
      - checkout
      # Check GHC and Cabal
      - run: cabal --version
      # Build
      - run: echo "Test"

workflows:
  version: 2.1
  builds:
    jobs:
      - make_build:
        filters:
          branches:
            only: master
      - cabal_build:
        filters:
          branches:
            only: master
      - test:
          requires:
            - cabal_build
          filters:
            branches:
              only: master
