version: 2
jobs:
  build:
    machine: true
    steps:
      # Check the Github files
      - checkout
      # Install GHC and Cabal
      - run: sudo apt-get update
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository -y ppa:hvr/ghc
      - run: sudo apt-get update
      - run: sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
      - run: export PATH="$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH"
      # Build
      - run: echo "Hello"
