version: 2
jobs:
  build:
    machine: true
    steps:
      # Check the Github files
      - checkout
      # Install GHC and Cabal
      - run:
        - name: Install GHC and Cabal
        - command: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:hvr/ghc
          sudo apt-get update
          sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
          export PATH="$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH"
      # Build
      - run: echo "Hello"
