version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      # Check the Github files
      - checkout
      # Install GHC and Cabal
      - run:
        - name: Test Cabal
        - command: |
          cabal --version
      # Build
      - run: echo "Hello"
